# Generated by Django 5.1.7 on 2025-03-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=100, verbose_name='Содержание')),
                ('likes', models.IntegerField(verbose_name='Количество лайков')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания')),
                ('is_published', models.BooleanField(verbose_name='Статус публикации')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
